stages:
  data_ingestion:
    cmd: python renalhealth_ai/cnn_classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - renalhealth_ai/cnn_classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-dataset


  prepare_base_mode:
    cmd: python renalhealth_ai/cnn_classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - renalhealth_ai/cnn_classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python renalhealth_ai/cnn_classifier/pipeline/stage_03_model_training.py
    deps:
      - renalhealth_ai/cnn_classifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-dataset
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AGUMENTATION
    outs:
      - artifacts/training/model_state_dict.pt
    
  
  evaluation:
    cmd: python renalhealth_ai/cnn_classifier/pipeline/stage_04_model_evaluation.py
    deps:
      - renalhealth_ai/cnn_classifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-dataset
      - artifacts/prepare_base_model
      - artifacts/training/model_state_dict.pt
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
